b4g/__init__.py
# Import the Flask basics
from logging.config import dictConfig
from flask import Flask, flash, redirect, url_for

# define logging dict
dictConfig({
    'version': 1,
    'formatters': {
        'default': {
            'format': '{"date": "%(asctime)s", '
                      '"log_level": "%(levelname)s", '
                      '"module": "%(module)s", '
                      '"message": "%(message)s"}'
         }
    },
    'handlers': {
        'wsgi': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://flask.logging.wsgi_errors_stream',
            'formatter': 'default'
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'default',
            'filename': 'app.log',
            'maxBytes': 1024000,
            'backupCount': 3
        }
    },
    'root': {
        'level': 'DEBUG',
        'handlers': [
            'wsgi',
            'file'
        ]
    }
})

# Define the App
app = Flask(__name__)

# Pull in the config
app.config.from_pyfile('../config.py')

# Import the module / component using their blueprints
# Initial frontend views
from b4g.home.views import home

# Register the Blueprints with the app
app.register_blueprint(home)

b4g/home/views.py
# external imports
from flask import Blueprint, render_template, request, \
    redirect, url_for, flash, jsonify
import requests

# Logging
import logging
logger = logging.getLogger(__name__)


home = Blueprint('home', __name__)
home.config = {}


@home.record
def record_params(setup_state):
  app = setup_state.app
  home.config = dict([(key, value) for (key, value) in app.config.items()])

# Helper functions


# def add_list_member(email):
#     MAILLIST = home.config['MAILGUN_MAILLIST']
#     MAILGUN_API_KEY = home.config['MAILGUN_API_KEY']
#     # TODO Add try/except for request fails
#     logger.info(f"Adding {email} to mail list")
#     return requests.post(
#         f"https://api.mailgun.net/v3/lists/{MAILLIST}/members",
#         auth=('api', MAILGUN_API_KEY),
#         data={
#             'subscribed': True,
#             'address': email
#         }
#     )
#
#
# def send_welcome_message(email):
#     MAILGUN_API_KEY = home.config['MAILGUN_API_KEY']
#     return requests.post(
#         "https://api.mailgun.net/v3/email.beforegreatness.com/messages",
#         auth=(
#             "api",
#             MAILGUN_API_KEY
#         ),
#         data={
#             "from": "Jeremy Schroeder <jeremy@beforegreatness.com>",
#             "to": email,
#             "subject": "Welcome to the Before Greatness Family!",
#             "template": "thank-you-for-subscribing"
#         }
#     )


# Basic site routes
@home.route('/', methods=['GET'])
def index():
    """ Main page """
    logo_url = url_for('static', filename='images/BG_MTN_LOGO_WHITE-256w.png')
    brand_logo_url = url_for('static', filename='images/BG_MTN_LOGO_horizontal-white-words.png')
    video_url = url_for(
        'static',
        filename='videos/stunning-rocky-mountain-landscape-timelapse-29603233_1280x720_24fps.mp4'
    )
    return render_template(
        'index.html',
        video_url=video_url,
        logo_url=logo_url,
        brand_logo_url=brand_logo_url
    )


# @home.route('/about', methods=['GET'])
# def about():
#     """ About Us page """
#     logo_url = url_for('static', filename='images/BG_MTN_LOGO_WHITE-256w.png')
#     brand_logo_url = url_for('static', filename='images/BG_MTN_LOGO_horizontal-white-words.png')
#     video_url = url_for(
#         'static',
#         filename='videos/pexels-eberhard-grossgasteiger-857251-540x360-25fps.mp4'
#     )
#     return render_template(
#         'about.html',
#         video_url=video_url,
#         logo_url=logo_url,
#         brand_logo_url=brand_logo_url
#     )


# @home.route('/maillist', methods=['POST'])
# def maillist_post():
#     """ Subscribe to mail list endpoint """
#     email = request.form.get('email')
#     added = add_list_member(email=email)
#     flash("Thank you for your interest, please check your email for updates.")
#     logger.info(added.text)
#     # Send thank you message
#     send_welcome_message(email=email)
#     return render_template('index.html')

b4g/templates/about.html
<!-- templates/index.html -->

{% extends "base.html" %}

{% block content %}

<div class="title b612-mono is-3 has-text-grey-lighter">
    about
</div>

<div class="container is-widescreen">
<div class="box has-text-left">
</br>
<p>At <b>before greatness</b>, we're not just a gym – we're a community dedicated to helping individuals achieve their fitness goals and discover their true potential. Our story is one of perseverance, strength, and an unyielding belief in the power of the human spirit.</p>
</br>
<h2 class="b612-mono has-text-weight-bold">our story</h2>
</br>
<p>Our founder, Jeremy, is not just a fitness enthusiast, but also a beacon of resilience. In 2006, Jeremy was diagnosed with cancer, a battle that he bravely fought and triumphed over. This experience instilled in him a profound appreciation for health and fitness, a passion that fueled the creation of <b>before greatness</b>.</p>
</br>
<p>Jeremy's journey through cancer recovery to peak fitness became a source of inspiration for others. He championed the idea that physical fitness is not only about building strength and endurance, but also about overcoming challenges, embracing personal growth, and celebrating the human spirit's indomitable resilience.</p>
</br>
<h2 class="b612-mono has-text-weight-bold">our mission</h2>
</br>
<p>Our mission at <b>before greatness</b> is to provide unique, targeted training that helps you excel in your chosen sport and in life. Whether it's improving your balance for longboarding, building strength for weightlifting, enhancing endurance for mountain biking, honing skills for snowboarding, or gearing up for a HYROX event, we've got you covered.</p>
</br>
<h2 class="b612-mono has-text-weight-bold">our commitment</h2>
</br>
<p>We are committed to creating an inclusive, motivating, and supportive environment. Our qualified trainers are here to guide you, and our community is here to uplift you. No matter your fitness level, age, or background, at <b>before greatness</b>, you will find a space where you can strive, grow, and achieve greatness – one workout at a time.</p>
</br>
<h2 class="b612-mono has-text-weight-bold">welcome to before greatness</h2>
</br>
<p>We welcome you to join us, where every sweat, every challenge overcome, and every goal achieved brings you one step closer to your personal greatness. Embrace the journey with us, and together, let's redefine what's possible!</p>
</br>
</div>
</div>




{% endblock %}

b4g/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>before greatness</title>
    
    <!-- Bulma Import -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    
    <!-- Bulma Social Sharing Import -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-social@2/css/all.min.css" />
    
    <!-- favicon link -->
     <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/bg_mtn_logo_black_circle_white_logo_icon.ico') }}">
    
    <!--Font Awesome-->
    <script src="https://kit.fontawesome.com/27ddd86667.js" crossorigin="anonymous"></script>

    <!-- fancy title font-->
    <!-- B612 Mono -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=B612+Mono">

    <!--    Add background style here for Jinja2 to work-->
    <style>
        .b612-mono {
            font-family: 'B612 Mono', serif;
        }

        /* CSS styles for the video background */
        #video-container {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
            z-index: -1;
        }

        #video-background {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
    </style>

</head>

<body>
<div id="video-container">
    <video id="video-background" autoplay muted loop>
    <!--    Video by eberhard grossgasteiger: https://www.pexels.com/video/beautiful-timelapse-of-the-night-sky-with-reflections-in-a-lake-857251/-->
          <source src="{{ video_url }}" type="video/mp4">
    </video>
</div>
<section class="hero is-transparent is-fullheight  ">

  <!-- Hero head: will stick at the top -->
    <div class="hero-head">
          <!-- NavBar -->
    <nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <!-- Add logo here -->
            <a class="navbar-item" href="{{ url_for('home.index') }}">
                <img src="{{ brand_logo_url }}" height="28">
            </a>
            <!-- burgers Mmmmmmm -->
            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navigation">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navigation" class="navbar-menu">
            <div class="navbar-start">
                <!-- For the left side NavBar -->
            </div>

            <div class="navbar-end ">
                <!-- For the right side NavBar -->
<!--                <a class="navbar-item b612-mono has-text-primary" href="{{ url_for('home.index') }}">-->
<!--                    home-->
<!--                </a>-->

<!--                <a href="https://blog.beforegreatness.com" class="navbar-item b612-mono has-text-primary">-->
<!--                    blog-->
<!--                </a>-->

            </div>
        </div>
    </nav>
</div>

  <!-- Hero content: will be in the middle -->
    <div class="hero-body">
            <div class="container is-widescreen has-text-centered">
                <!-- messages from FLask -->
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="notification is-primary">
                <button class="delete"></button>
                  {{ messages[0] }}
                </div>
                {% endif %}
            {% endwith %}

               {% block content %}
                    <!-- Flask content gets inserted here -->
               {% endblock %}
            </div>
    </div>

<!-- JavaScript to make burger menu work -->
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const $nbBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
        if ($nbBurgers.length < 1) {
            return;
        }
        $nbBurgers.forEach( el => {
            el.addEventListener('click', () => {
                const target = el.dataset.target;
                const $target = document.getElementById(target);
                el.classList.toggle('is-active');
                $target.classList.toggle('is-active');
            });
        });
    });
</script>

<!--    JavaScript to delete notifications. -->
<script>
    document.addEventListener('DOMContentLoaded', () => {
  (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
    const $notification = $delete.parentNode;

    $delete.addEventListener('click', () => {
      $notification.parentNode.removeChild($notification);
    });
  });
});
</script>

</body>

</html>

b4g/templates/index.html
<!-- templates/index.html -->

{% extends "base.html" %}

{% block content %}
        <div class="columns is-mobile is-centered">
            <figure class="image ">
                <img src="{{ logo_url }}">
            </figure>
        </div>
        <br/>
        <div class="title b612-mono is-4 has-text-grey-lighter">
            before greatness
        </div>
</br>
        <div class="tabs is-centered">
          <ul>
<!--          <li>-->
<!--            &lt;!&ndash; YouTube&ndash;&gt;-->
<!--              <a href="https://www.youtube.com/channel/UCkiEGgIwNLrKuDUwCkSrOwQ" target="_blank">-->
<!--              <div class="icon-text">-->
<!--              <span class="icon has-text-success">-->
<!--                <i class="fa-brands fa-square-youtube"></i>-->
<!--              </span>-->
<!--            </div>-->
<!--              </a>-->
<!--          </li>-->
          </ul>
        </div>


<br/>

{% endblock %}